### ISSUE TITLE
'copied' appended to end of ln invoice on checkout

### ISSUE THREAD

**Issue by KayBeSee** [Blockstream/ln-wordpress-store#1]
I noticed that there is a minor bug when copying a lightning invoice during checkout.

When the user clicks the copy button, it copies the invoice but appends `copied` to the end too which causes the invoice the be invalid when ran through validators.

An example: `lnbc533095920p1pwuru0wpp5zlq3zqzmzxf79sla36u9vhy77xemmht3urwg0eqdfuu953005qfsdrqgfkx7cmtwd68yetpd5s9xar0wfjn5gp59cunjgz42dzzqen0wgszysnpvd4jqjtwypxhjgzyv9ujygznw35kx6m9wgs8sgp3xqyjw5qcqp2rzjq239sjk3c4pspuzhv5r76ca8junu25c5v2zgduj9s2kqwy2n6x9qxzrcvyqq9vqqqqqqqqlgqqqqqqgqjqhrm8lesk57hxv2727wvg2p4u4cutwgp40p9zum4u42wygw0sckqstlgqqthkch0yh9pd8ken68s3ketsmrh5jy73ntkt24ezw75p6wcp9090v5copied`

**Comment by brandoncurtis** [comment]
looks like this has been fixed: https://twitter.com/BlockstreamHelp/status/1199511027483914240
